### ISSUE TITLE
Player Unnecessarily Transcodes Video for Streams with DTS Audio

### ISSUE THREAD

**Issue by PersonOfInterest523** [jellyfin/jellyfin-webos#105]
When attempting to play an HEVC video with DTS audio, the player correctly begins transcoding the audio because of the previous issue described in #56. However, the player also transcodes the video into H.264 with the listed reason being "The container is not supported" even though the container is mkv, which is supported. If I disable the "Allow video playback that requires transcoding" setting for the user, it correctly plays the video back in HEVC and only the audio is transcoded, but this is a workaround, which prevents the playback of other videos and does not address the underlying issue.

The only two files I have with DTS audio are both 4K HEVC HDR videos in mkv containers, and this issue occurs for both of them. It does not occur for 4K HEVC HDR videos in mkv containers with audio other than DTS. The following is the video and audio info for one of the videos having the issue:
```
Video
Title: 4K HEVC HDR
Codec: HEVC
Profile: Main 10
Level: 153
Resolution: 3840x2160
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 28227 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1


Audio
Title: English - DTS-HD MA - 5.1 - Default
Language: eng
Codec: DTS
Profile: DTS-HD MA
Layout: 5.1
Channels: 6 ch
Bitrate: 3686 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes
Forced: No
External: No
```

Please let me know if there's anything else I should try or any more info that you need.

**Comment by anthonylavado** [comment]
What version of Jellyfin are you using? The split transcoding requires at least 10.8+...

**Comment by PersonOfInterest523** [comment]
I am using version 10.8.4

**Comment by stoically** [comment]
Sounds like https://github.com/jellyfin/jellyfin/issues/8043

**Comment by Otako77** [comment]
The same Problem on my LG C1 latest Firmware and latest Jellyfin App. Jellyfin latest 10.8.7, DTS-AAC Transcoding AND unnecessarily HEVC-H.264 transcoding.

**Comment by dabohda** [comment]
Same Problem here with the latest docker linuxserver/jellyfin 10.8.8 and lg c2 latest firmware. The player also transcodes the video into H.264 with the listed reason being "The container is not supported"

**Comment by dabohda** [comment]
Full HD movies with dts sound works like it should. Only the audio stream is transcoded and the movie is send in direct stream mode. With both x264 and x265 video codec. But with 4k movies the video stream is transcoded.

**Comment by Otako77** [comment]
https://github.com/jellyfin/jellyfin-webos/issues/118#issuecomment-1367695609

**Comment by Hooloovoo** [comment]
> If I disable the "Allow video playback that requires transcoding" setting for the user, it correctly plays the video back in HEVC and only the audio is transcoded

Great work figuring this out. Same here. Obviously a proper fix would be better. Please let me know if any details or logs from me would help.

**Comment by Hooloovoo** [comment]
I am still seeing this on 10.8.9 (server in Docker container on Ubuntu) -- is that expected? PR #9092 says it fixed this and I thought from looking at the release notes for 10.8.9 (https://github.com/jellyfin/jellyfin/releases/tag/v10.8.9) that it included this fix.

**Comment by Killface1980** [comment]
The same issue came up in 10.10 again.
It was working as expected, since a reinstall most videos are transcoded without any need.
Also, pfrefer fMP4 is ignored completely.

**Comment by dmitrylyzo** [comment]
@Killface1980 Try disabling HEVC encoding in the Dashboard + disable fMP4 on the TV.

**Comment by 0xBADEAFFE** [comment]
> @Killface1980 Try disabling HEVC encoding in the Dashboard + disable fMP4 on the TV.

Unfortunately, this does not solve the problem.

**Comment by PersonOfInterest523** [comment]
Update: I recently tried to play the file that originally caused the problem, and it worked perfectly without transcoding, so either this bug has been fixed or I misidentified it in the first place. 
The reason I say that I might have misidentified it is that the video transcodes when using the PGS subtitle track attached to the file. This is correct behavior, and when I turn off the subtitle track the transcoding stops. It is possible that the two files I had with PGS subtitles also happened to be the two files I had with DTS audio, and I misattributed what was causing the transcoding.
However, I cannot verify what was causing the transcoding when I first opened this issue. As I said in my initial comment, the listed reason was "The container is not supported," which didn't make sense. Now, when the video transcodes the listed reason is "The subtitle codec is not supported," which is correct. Therefore, either there was a real bug causing transcoding, which was fixed, or there was a silly bug in listing the correct error message, which was fixed.

I don't know whether this issue should be closed because it sounds like other people had a similar problem, and I don't know if they still have it.

**Comment by PersonOfInterest523** [comment]
Further update: I don't think I misattributed the bug because I mention in my original post that the video was transcoded into H.264, but when transcoding because of the subtitles, it stays in HEVC.

That doesn't change the fact that it works now, and the bug appears to be fixed (at least for me).

**Comment by jbaiter** [comment]
I'm running 10.10.7 and am still encountering this bug.
I have a HEVC 2160p video with 16bit DTS-HD Master Audio.
When playing the video from Jellyfin WebOS version on my LG C3 TV, both the video and the audio are transcoded, with the reason given being "Audio Format not supported".

**However**, I can not always reproduce this. After a few retries, Direct Streaming of video with only the audio transcoded seems to work.

Here's the log of four attempts to play the video, with direct play only succeeding on the last two attempts:

<details>
<summary>View Logs</summary>
```
[21:51:50] [INF] [50] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for jojo. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[21:51:50] [INF] [8] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media-nas/movies/jellyfin/video.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -low_power 1 -preset veryfast -b:v 67146314 -maxrate 67146314 -bufsize 134292628 -profile:v:0 high -level 51 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,procamp_vaapi=b=16,tonemap_vaapi=format=nv12:p=bt709:t=bt709:m=bt709:extra_hw_frames=32,hwmap=derive_device=qsv,format=qsv" -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/3563cd48af4590b02e2452e64c8a2529%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/3563cd48af4590b02e2452e64c8a2529.m3u8"
[21:52:10] [INF] [14] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /cache/transcodes/3563cd48af4590b02e2452e64c8a2529.m3u8
[21:52:11] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[21:52:11] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /cache/transcodes/3563cd48af4590b02e2452e64c8a2529.m3u8
[21:52:12] [INF] [72] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.10.7 playing 2001: Odyssee im Weltraum. Stopped at 12930 ms
[21:52:21] [INF] [14] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for jojo. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[21:52:22] [INF] [72] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media-nas/movies/jellyfin/video.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_qsv -low_power 1 -preset veryfast -b:v 67146314 -maxrate 67146314 -bufsize 134292628 -profile:v:0 high -level 51 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,procamp_vaapi=b=16,tonemap_vaapi=format=nv12:p=bt709:t=bt709:m=bt709:extra_hw_frames=32,hwmap=derive_device=qsv,format=qsv" -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/1771ef7aa675f464ba13e6ebda3adec4%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/1771ef7aa675f464ba13e6ebda3adec4.m3u8"
[21:52:48] [INF] [16] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[21:54:00] [INF] [72] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[21:55:59] [INF] [14] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /cache/transcodes/1771ef7aa675f464ba13e6ebda3adec4.m3u8
[21:55:59] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[21:55:59] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /cache/transcodes/1771ef7aa675f464ba13e6ebda3adec4.m3u8
[21:56:01] [INF] [55] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.10.7 playing 2001: Odyssee im Weltraum. Stopped at 317378 ms
[21:56:12] [INF] [58] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[21:58:12] [INF] [11] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[21:58:47] [INF] [54] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for jojo. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[21:58:48] [INF] [54] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -readrate 10 -fflags +genpts -f matroska  -i file:"/media-nas/movies/jellyfin/video.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/02d9952271030504062c54f1f6690438%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/02d9952271030504062c54f1f6690438.m3u8"
[21:59:00] [INF] [30] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[21:59:21] [INF] [24] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /cache/transcodes/02d9952271030504062c54f1f6690438.m3u8
[21:59:22] [INF] [31] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[21:59:22] [INF] [24] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -ss 00:25:06.922 -readrate 10 -fflags +genpts -f matroska  -i file:"/media-nas/movies/jellyfin/video.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 251 -hls_segment_filename "/cache/transcodes/02d9952271030504062c54f1f6690438%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/02d9952271030504062c54f1f6690438.m3u8"
```
</details>

<details>
<summary>mediainfo for the file</summary>
```
General
Unique ID                                : 29853603998285292231206966867312875878 (0x167598512FE924E93FFE32F655319966)
Complete name                            : video.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 69.8 GiB
Duration                                 : 2 h 28 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 67.1 Mb/s
Frame rate                               : 23.976 FPS
Encoded date                             : 2019-03-26 05:09:10 UTC
Writing application                      : mkvmerge v31.0.0 ('Dolores In A Shoestand') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 28 min
Bit rate                                 : 62.2 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.313
Stream size                              : 64.7 GiB (93%)
Title                                    : MPEG-H HEVC Video / 62197 kbps / 2160p / 23.976 fps / 16:9 / Main 10 @ Level 5.1 @ High / 10 bits / HDR10 / BT.2020
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 992 cd/m2
Maximum Frame-Average Light Level        : 282 cd/m2

Audio #1
ID                                       : 2
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 2 h 28 min
Bit rate mode                            : Variable
Bit rate                                 : 2 197 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 2.28 GiB (3%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
```
</details>
